# Table names
TABLENAME_USER = 'user'
TABLENAME_TGUSER = 'tguser'
TABLENAME_MESSAGE = 'message'
TABLENAME_CHAT = 'chat'

# Database settings
CONNECTION_STR = ''
DATABASE_DRIVER = 'DB_DRIVER'
DATABASE_USER = 'DB_USER'
DATABASE_PASS = 'DB_PASS'
DATABASE_HOST = 'DB_HOST'
DATABASE_NAME = 'DB_NAME'
DATABASE_PORT = 'DB_PORT'