# Table names
TABLENAME_USER = 'user'
TABLENAME_TGUSER = 'tguser'
TABLENAME_MESSAGE = 'message'
TABLENAME_CHAT = 'chat'
TABLENAME_TASK = 'task'

# Database settings
CONNECTION_STR = ''
DATABASE_DRIVER = 'DB_DRIVER'
DATABASE_USER = 'DB_USER'
DATABASE_PASS = 'DB_PASS'
DATABASE_HOST = 'DB_HOST'
DATABASE_NAME = 'DB_NAME'
DATABASE_PORT = 'DB_PORT'

TEST_DATABASE_HOST = 'TEST_DB_HOST'
TEST_DATABASE_PASS = 'TEST_DB_PASS'
TEST_DATABASE_PORT = 'TEST_DB_PORT'
TEST_DATABASE_USER = 'TEST_DB_USER'
TEST_DATABASE_DRIVER = 'TEST_DB_DRIVER'
TEST_DATABASE_NAME = 'TEST_DB_NAME'

# Telegram token
TELEGRAM_TOKEN = 'TELEGRAM_TOKEN'